name: 'Lints a React App'
description: 'This action will automate the process of linting a react app.'

runs: 
  using: 'composite'
  steps: 
    # Clean install dependencies (https://docs.npmjs.com/cli/v7/commands/npm-ci)
    - name : Installing dependencies...
      run : npm ci
      shell: bash

    # Lint the react app
    - name : Linting react app...
      run : npm run lint
      shell: bash