# This action will automatically deploy the website on changes to main.
name: CI/CD
on: [push]

jobs:
  lint:
    name: Lint App
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Linting...
      uses: ./.github/actions/lint
  test:
    name: Test App
    needs: lint
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Testing...
      uses: ./.github/actions/test
  build:
    if: github.ref == 'refs/heads/main'
    name: Build App
    needs: test
    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2
    - name: Building...
      uses: ./.github/actions/build
    - name: Uploading build artifacts...
      uses: actions/upload-artifact@v2
      with:
        name : react-app-build
        path : build/
  # deploy:
  #   if: github.ref == 'refs/heads/main'
  #   name: Deploy App
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Downloading build artifacts...
  #     uses: actions/download-artifact@v2
  #     with:
  #       name: react-app-build
  #       path: build/
  #   - name: Deploying...
  #     uses: ./.github/actions/deploy
