# # This action will test the code whenever a PR is submitted to the main branch.
# name: Test

# on:
#   pull_request:
#     branches: [ main ]

# jobs:
#   build:

#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2

#     - name: Deploy react app to github pages
#       uses: tanwanimohit/deploy-react-to-ghpages@v1.0.1
