# This action will test the code whenever a PR is submitted to the main branch.
name: Test

on:
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci # do a clean install (faster in CI/CD than npm install)
        shell: bash
      - run: npm run build # build the project
        shell: bash
      - run: npm run lint # lint the project
        shell: bash
